networks:
  app_network:

volumes:
  pd-db:
    driver: local
  secondary-db:
    driver: local

    
services:
  postgres:
    image: postgres:17.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}       
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}   
    ports:
      - '5432:5432'
    volumes: 
      - pd-db:/var/lib/postgresql/data
    networks:
      - app_network
  postgres_secondary:
    image: postgres:17.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
    ports:
      - '5433:5432'
    volumes:
      - secondary-db:/var/lib/postgresql/data
    networks:
      - app_network